# Copyright 2026 Christopher Barber
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# Type stub for the `_native` nanobind extension (built from cpp/binding.cpp).
#
# The compiled `_native` module is loaded at runtime through scikit-build-core's
# editable redirector, which static analyzers (PyCharm, mypy) cannot follow. This
# checked-in stub gives them the interface so `_native` and the symbols
# re-exported from it in `__init__.py` resolve.
#
# GENERATED by `pixi run stubgen` (scripts/stubgen.py): it runs nanobind's stubgen
# and then re-applies the edits nanobind cannot infer — this header, and the
# return types of `parse_events` / `lex` / `rule_spans` (reported as `object`).
# Edit scripts/stubgen.py, not this file.
"""antlr-pyfacade: Python binding over the official ANTLR4 C++ runtime"""

from collections.abc import Sequence


class AtnShape:
    @property
    def grammar_type(self) -> int: ...

    @property
    def num_states(self) -> int: ...

    @property
    def num_decisions(self) -> int: ...

    @property
    def num_rules(self) -> int: ...

    @property
    def max_token_type(self) -> int: ...

    def __repr__(self) -> str: ...

def atn_shape(serialized: Sequence[int]) -> AtnShape:
    """Deserialize a serialized ATN int list and return its shape."""

class ParseError:
    @property
    def line(self) -> int: ...

    @property
    def column(self) -> int: ...

    @property
    def start(self) -> int: ...

    @property
    def stop(self) -> int: ...

    @property
    def message(self) -> str: ...

    def __repr__(self) -> str: ...

class LexerSpec:
    def __init__(self, grammar_file_name: str, literal_names: Sequence[str], symbolic_names: Sequence[str], rule_names: Sequence[str], channel_names: Sequence[str], mode_names: Sequence[str], serialized: Sequence[int]) -> None: ...

class ParserSpec:
    def __init__(self, grammar_file_name: str, literal_names: Sequence[str], symbolic_names: Sequence[str], rule_names: Sequence[str], serialized: Sequence[int]) -> None: ...

class Token:
    def getType(self) -> int: ...

    def getText(self) -> str: ...

    def getLine(self) -> int: ...

    def getCharPositionInLine(self) -> int: ...

class ParseTree:
    pass

class RuleContext(ParseTree):
    def getRuleIndex(self) -> int: ...

class ParserRuleContext(RuleContext):
    def getStart(self) -> Token: ...

    def getStop(self) -> Token: ...

class TerminalNode(ParseTree):
    def getSymbol(self) -> Token: ...

class ErrorNode(TerminalNode):
    pass

class ParseTreeListener:
    def __init__(self) -> None: ...

    def visitTerminal(self, arg: TerminalNode, /) -> None: ...

    def visitErrorNode(self, arg: ErrorNode, /) -> None: ...

    def enterEveryRule(self, arg: ParserRuleContext, /) -> None: ...

    def exitEveryRule(self, arg: ParserRuleContext, /) -> None: ...

def parse_count(parser_spec: ParserSpec, lexer_spec: LexerSpec, text: str, start_rule: int) -> dict:
    """
    Diagnostic: parse + walk with a native counting listener (no Python crossing).
    """

def parse_walk(parser_spec: ParserSpec, lexer_spec: LexerSpec, text: str, start_rule: int, listener: ParseTreeListener) -> None:
    """
    Diagnostic escape hatch: parse + walk the tree, dispatching to a Python ParseTreeListener (slow per-node FFI path).
    """

def parse_events(parser_spec: ParserSpec, lexer_spec: LexerSpec, text: str, start_rule: int, rule_mask: Sequence[int] | None = None, token_mask: Sequence[int] | None = None) -> tuple[bytes, list[ParseError]]:
    """
    Parse and return (events, errors): a bulk flat int32 event buffer of 4*N values (kind, payload, start, stop) as bytes, and a list of SyntaxError diagnostics collected during the parse. Optional rule_mask/token_mask (lists of indices to keep) filter events natively. The default stderr error listener is suppressed.
    """

def parse_stage_times(parser_spec: ParserSpec, lexer_spec: LexerSpec, text: str, start_rule: int) -> dict:
    """
    Diagnostic: dict of per-stage seconds (input_decode, lex_fill, parse_tree, walk) plus token/event/codepoint counts.
    """

def lex(lexer_spec: LexerSpec, text: str, token_mask: Sequence[int] | None = None) -> tuple[bytes, list[ParseError]]:
    """
    Run only the lexer and return (tokens, errors): a flat int32 buffer of 4*N values (type, channel, start, stop) as bytes (EOF omitted), and a list of ParseError diagnostics. Optional token_mask (list of token types to keep) drops the rest natively. The cheap stage used to chunk input for walk_parallel without a full parse.
    """

def rule_spans(parser_spec: ParserSpec, lexer_spec: LexerSpec, text: str, start_rule: int, rule_mask: Sequence[int] | None = None, outermost: bool = True) -> tuple[bytes, list[ParseError]]:
    """
    Parse (entirely in C++) and return (spans, errors): a flat int32 buffer of 3*N values (rule_index, start, stop) for each parse-tree rule kept by rule_mask (None = all), plus a list of ParseError diagnostics. With outermost=True a matched rule's subtree is skipped. Used for rule-based chunking.
    """
