"""Generate a grammar-specific event-listener facade from stock ANTLR Python
parser metadata.

Reads ``ruleNames`` + token name lists from an already-generated ANTLR Python
parser module (no annotated grammar, no extra inputs) and emits a
``<Grammar>EventListener`` base class: named ``enter<Rule>`` / ``exit<Rule>``
no-op stubs, ``visitTerminal`` / ``visitError`` stubs, token-type constants, and
a ``walk`` method that runs the bulk native event stream. The base subclasses
``FacadeListener``, so callbacks can call ``self.line_col()`` for the current
event's source position.

The generated surface mirrors the stock ANTLR listener so consumers write the
same code; the difference is that callbacks are driven by a flat event buffer
rather than a Python parse-tree walk. Usage (console script or module):

    antlr-pyfacade mypkg.generated.MyParser My -o my_listener.py
"""

from __future__ import annotations

import argparse
import importlib
import sys


def _ident(name: str) -> str:
    return name[0].upper() + name[1:]


def generate(parser_qualname: str, grammar: str) -> str:
    mod = importlib.import_module(parser_qualname)
    parser_cls = getattr(mod, parser_qualname.rsplit(".", 1)[1])
    rule_names: list[str] = list(parser_cls.ruleNames)
    symbolic: list[str] = list(parser_cls.symbolicNames)
    literal: list[str] = list(parser_cls.literalNames)

    # token-type constants: symbolic name if present, else a literal-derived one
    tok_consts: list[tuple[str, int]] = []
    for ttype, sym in enumerate(symbolic):
        if ttype == 0:
            continue  # type 0 is unused / EOF sentinel
        if sym and sym != "<INVALID>":
            tok_consts.append((sym, ttype))
        elif ttype < len(literal) and literal[ttype] not in ("<INVALID>", ""):
            tok_consts.append((f"T__{ttype}", ttype))

    out: list[str] = []
    w = out.append
    w('"""GENERATED by antlr-pyfacade — do not edit by hand.\n')
    w(f"Event-listener facade for the {grammar} grammar. Subclass "
      f"{grammar}EventListener,")
    w("override the callbacks you care about, then call "
      ".walk(text, LexerCls, ParserCls).")
    w('"""')
    w("")
    w("from __future__ import annotations")
    w("")
    w("from antlr_pyfacade import FacadeListener, drive, load_specs")
    w("")
    w("")
    w(f"class {grammar}EventListener(FacadeListener):")
    w(f"    ruleNames = {rule_names!r}")
    w(f"    START_RULE = 0  # {rule_names[0]}")
    w("")
    w("    # token-type constants")
    for name, ttype in tok_consts:
        w(f"    {name} = {ttype}")
    w("")
    for name in rule_names:
        cap = _ident(name)
        w(f"    def enter{cap}(self) -> None:")
        w("        pass")
        w("")
        w(f"    def exit{cap}(self) -> None:")
        w("        pass")
        w("")
    w("    def visitTerminal(self, token_type: int, text: str) -> None:")
    w("        pass")
    w("")
    w("    def visitError(self, token_type: int, text: str) -> None:")
    w("        pass")
    w("")
    w("    def walk(self, text: str, lexer_cls, parser_cls, *, "
      "filtered: bool = True) -> None:")
    w("        parser_spec, lexer_spec = load_specs(lexer_cls, parser_cls)")
    w(f"        drive(self, {grammar}EventListener, parser_spec, lexer_spec,")
    w("              text, self.START_RULE, filtered=filtered)")
    w("")
    return "\n".join(out)


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(
        prog="antlr-pyfacade",
        description="Generate a <Grammar>EventListener facade from a "
        "stock-generated ANTLR Python parser module.",
    )
    parser.add_argument(
        "parser_module",
        help="Importable dotted path to the generated parser module "
        "(e.g. mypkg.generated.MyParser).",
    )
    parser.add_argument("grammar", help="Grammar name prefix for the facade class.")
    parser.add_argument(
        "-o", "--output", help="Write to this file instead of stdout."
    )
    args = parser.parse_args(argv)

    source = generate(args.parser_module, args.grammar)
    if args.output:
        with open(args.output, "w", encoding="utf-8") as fh:
            fh.write(source)
    else:
        sys.stdout.write(source)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
