# Copyright 2026 Christopher Barber
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""Generate a grammar-specific event-listener facade from ANTLR parser metadata.

Reads `ruleNames` + token name lists from an already-generated ANTLR Python parser
module (no annotated grammar, no extra inputs) and emits a `<Grammar>EventListener`
base class: named `enter<Rule>` / `exit<Rule>` no-op stubs, `visitTerminal` /
`visitError` stubs, token-type constants, and a `walk` method that runs the bulk
native event stream. The base subclasses
[FacadeListener][antlr_pyfacade.FacadeListener], so callbacks can call
`self.line_col()` for the current event's source position.

The generated surface mirrors the stock ANTLR listener so consumers write the same
code; the difference is that callbacks are driven by a flat event buffer rather
than a Python parse-tree walk. Usage (console script or module):

    antlr-pyfacade mypkg.generated.MyParser My -o my_listener.py
"""

from __future__ import annotations

import argparse
import importlib
import sys
from textwrap import dedent

from antlr_pyfacade import __version__

# TODO - add doc strings


def _ident(name: str) -> str:
    return name[0].upper() + name[1:]


def generate(parser_qualname: str, grammar: str) -> str:
    mod = importlib.import_module(parser_qualname)
    parser_cls = getattr(mod, parser_qualname.rsplit(".", 1)[1])
    rule_names: list[str] = list(parser_cls.ruleNames)
    symbolic: list[str] = list(parser_cls.symbolicNames)
    literal: list[str] = list(parser_cls.literalNames)

    listener_cls = f"{grammar.capitalize()}EventListener"

    # token-type constants: symbolic name if present, else a literal-derived one
    tok_consts: list[tuple[str, int]] = []
    for ttype, sym in enumerate(symbolic):
        if ttype == 0:
            continue  # type 0 is unused / EOF sentinel
        if sym and sym != "<INVALID>":
            tok_consts.append((sym, ttype))
        elif ttype < len(literal) and literal[ttype] not in ("<INVALID>", ""):
            tok_consts.append((f"T__{ttype}", ttype))

    # token_lines / rule_methods carry their own class-body indentation; the
    # template's placeholders sit at the base column so the content lands right.
    token_lines = "\n".join(f"    {name} = {ttype}" for name, ttype in tok_consts)
    rule_methods = "".join(
        f"""    def enter{cap}(self) -> None:
        pass

    def exit{cap}(self) -> None:
        pass

"""
        for cap in map(_ident, rule_names)
    )

    # Emit the rule-name list as a double-quoted literal (rule names are ANTLR
    # identifiers, so no escaping is needed) so the generated file is
    # ruff-format-clean as written — repr() would use single quotes.
    rule_names_src = "[" + ", ".join(f'"{name}"' for name in rule_names) + "]"

    # dedent() must run before .format(): an f-string would interpolate the
    # multi-line token_lines/rule_methods first, and their lower indentation would
    # then throw off dedent's common-prefix calculation.
    return dedent(
        '''\
        # GENERATED by antlr-pyfacade — do not edit by hand.
        """
        Event-listener facade for the {grammar} grammar. Subclass {cls},
        override the callbacks you care about, then call .walk(text, LexerCls, ParserCls).
        """

        from __future__ import annotations

        from typing import ClassVar

        from antlr_pyfacade import FacadeListener, load_specs


        class {cls}(FacadeListener):
            ruleNames: ClassVar[list[str]] = {rule_names_src}
            START_RULE = 0  # {rule0}

            # token-type constants
        {token_lines}

        {rule_methods}    def visitTerminal(self, token_type: int, text: str) -> None:
                pass

            def visitError(self, token_type: int, text: str) -> None:
                pass

            def walk(
                self,
                text: str,
                lexer_cls: type,
                parser_cls: type,
                *,
                start_rule: int | str | None = None,
                filtered: bool = True,
            ) -> {cls}:
                parser_spec, lexer_spec = load_specs(lexer_cls, parser_cls)
                rule = self._resolve_start_rule({cls}, start_rule)
                self.drive(parser_spec, lexer_spec, text, rule, filtered=filtered)
                return self
        '''
    ).format(
        grammar=grammar,
        cls=listener_cls,
        rule_names_src=rule_names_src,
        rule0=rule_names[0],
        token_lines=token_lines,
        rule_methods=rule_methods,
    )


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(
        prog="antlr-pyfacade",
        description="Generate a <Grammar>EventListener facade from a "
        "stock-generated ANTLR Python parser module.",
    )
    parser.add_argument(
        "--version", action="version", version=f"%(prog)s {__version__}"
    )
    parser.add_argument(
        "parser_module",
        help="Importable dotted path to the generated parser module "
        "(e.g. mypkg.generated.MyParser).",
    )
    parser.add_argument("grammar", help="Grammar name prefix for the facade class.")
    parser.add_argument("-o", "--output", help="Write to this file instead of stdout.")
    args = parser.parse_args(argv)

    source = generate(args.parser_module, args.grammar)
    if args.output:
        with open(args.output, "w", encoding="utf-8") as fh:
            fh.write(source)
    else:
        sys.stdout.write(source)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
