# GENERATED by antlr-pyfacade — do not edit by hand.
"""
Event-listener facade for the JSON grammar. Subclass JSONEventListener,
override the callbacks you care about, then call .walk(text, LexerCls, ParserCls).
"""

from __future__ import annotations

from antlr_pyfacade import FacadeListener, drive, load_specs


class JSONEventListener(FacadeListener):
    ruleNames = ['json', 'obj', 'pair', 'arr', 'value']
    START_RULE = 0  # json

    # token-type constants
    T__1 = 1
    T__2 = 2
    T__3 = 3
    T__4 = 4
    T__5 = 5
    T__6 = 6
    T__7 = 7
    T__8 = 8
    T__9 = 9
    STRING = 10
    NUMBER = 11
    WS = 12

    def enterJson(self) -> None:
        pass

    def exitJson(self) -> None:
        pass

    def enterObj(self) -> None:
        pass

    def exitObj(self) -> None:
        pass

    def enterPair(self) -> None:
        pass

    def exitPair(self) -> None:
        pass

    def enterArr(self) -> None:
        pass

    def exitArr(self) -> None:
        pass

    def enterValue(self) -> None:
        pass

    def exitValue(self) -> None:
        pass

    def visitTerminal(self, token_type: int, text: str) -> None:
        pass

    def visitError(self, token_type: int, text: str) -> None:
        pass

    def walk(self, text: str, lexer_cls: type, parser_cls: type, *, start_rule: int | str | None = None,
             filtered: bool = True) -> "JSONEventListener":
        parser_spec, lexer_spec = load_specs(lexer_cls, parser_cls)
        rule = self._resolve_start_rule(JSONEventListener, start_rule)
        drive(self, JSONEventListener, parser_spec, lexer_spec,
              text, rule, filtered=filtered)
        return self
