# Copyright 2026 Christopher Barber
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""Regenerate `src/antlr_pyfacade/_native.pyi` and re-apply the hand edits.

`pixi run stubgen` runs this. nanobind's stubgen overwrites the whole stub (header
included) and reports a couple of return types it can't infer as `object`. This
runs stubgen, then re-applies the documented edits so the committed stub is
produced directly — edit this script, not the `.pyi`, to change them.
"""

from __future__ import annotations

import re
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
STUB = ROOT / "src" / "antlr_pyfacade" / "_native.pyi"

# Functions whose return nanobind reports as `object` (it can't infer
# `nb::make_tuple(...)`), with the real type to substitute.
RETURN_TYPES = {
    "parse_events": "tuple[bytes, list[ParseError]]",
    "lex": "tuple[bytes, list[ParseError]]",
}

# License header + maintenance note, prepended ahead of stubgen's module
# docstring (stubgen drops everything above it).
HEADER = """\
# Copyright 2026 Christopher Barber
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# Type stub for the `_native` nanobind extension (built from cpp/binding.cpp).
#
# The compiled `_native` module is loaded at runtime through scikit-build-core's
# editable redirector, which static analyzers (PyCharm, mypy) cannot follow. This
# checked-in stub gives them the interface so `_native` and the symbols
# re-exported from it in `__init__.py` resolve.
#
# GENERATED by `pixi run stubgen` (scripts/stubgen.py): it runs nanobind's stubgen
# and then re-applies the edits nanobind cannot infer — this header, and the
# return types of `parse_events` / `lex` (which nanobind reports as `object`).
# Edit scripts/stubgen.py, not this file.
"""


def main() -> int:
    subprocess.run(
        [
            sys.executable,
            "-m",
            "nanobind.stubgen",
            "-m",
            "antlr_pyfacade._native",
            "-o",
            str(STUB),
        ],
        check=True,
    )

    text = STUB.read_text(encoding="utf-8")

    for name, ret in RETURN_TYPES.items():
        text, n = re.subn(
            rf"(def {re.escape(name)}\([^\n]*\)) -> object:",
            rf"\1 -> {ret}:",
            text,
        )
        if n != 1:
            raise SystemExit(
                f"stubgen post-process: expected exactly one '{name}(...) -> object', "
                f"found {n}. nanobind output changed — update scripts/stubgen.py."
            )

    STUB.write_text(HEADER + text, encoding="utf-8")
    print(f"wrote {STUB.relative_to(ROOT)} (stubgen + hand edits applied)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
